// Copyright (C) 2026 Jonas Immanuel Frey - Licensed under GPLv2. See LICENSE file for details.
// Generated by tee_dunker ESP32 flasher — do not edit manually

#include <WiFi.h>
#include <WebServer.h>
#include <Preferences.h>
#include <WebSocketsClient.h>
#include <ArduinoJson.h>

// ── Flash-time defaults (overridden by NVS if saved values exist) ──
const char* S_WIFI_SSID_DEFAULT = "MyNetwork";
const char* S_WIFI_PASSWORD_DEFAULT = "changeme";
const char* S_SERVER_IP_DEFAULT = "192.168.1.100";
const int N_SERVER_PORT_DEFAULT = 8077;
const int N_PIN_IN1 = 17;
const int N_PIN_IN2 = 16;
const int N_PIN_IN3 = 4;
const int N_PIN_IN4 = 2;

// ── Runtime config (loaded from NVS or defaults) ──
String s_wifi_ssid;
String s_wifi_password;
String s_server_ip;
int n_server_port;
float n_turn__loop;
int n_turn__last;
int n_min_duration;
float n_rpm;

// ── 28BYJ-48 half-step driver (no library) ──
// 28BYJ-48 with ULN2003 in half-step mode: 4096 half-steps per revolution
// gear ratio 63.68395:1, 64 half-steps per motor revolution, 64 * 63.68395 ≈ 4076
// commonly rounded to 4096 for simplicity
const int N_HALFSTEP_PER_REV = 4096;

// half-step sequence: 8 phases
// each phase sets IN1-IN4 high/low
const int A_N_HALFSTEP[8][4] = {
    {1, 0, 0, 0},  // phase 0
    {1, 1, 0, 0},  // phase 1
    {0, 1, 0, 0},  // phase 2
    {0, 1, 1, 0},  // phase 3
    {0, 0, 1, 0},  // phase 4
    {0, 0, 1, 1},  // phase 5
    {0, 0, 0, 1},  // phase 6
    {1, 0, 0, 1},  // phase 7
};

int n_phase = 0; // current phase index 0-7
unsigned long n_us_step_delay = 2000; // microseconds between half-steps

void f_set_phase(int n_p) {
    digitalWrite(N_PIN_IN1, A_N_HALFSTEP[n_p][0]);
    digitalWrite(N_PIN_IN2, A_N_HALFSTEP[n_p][1]);
    digitalWrite(N_PIN_IN3, A_N_HALFSTEP[n_p][2]);
    digitalWrite(N_PIN_IN4, A_N_HALFSTEP[n_p][3]);
}

void f_stepper_off() {
    // de-energize all coils to save power and reduce heat
    digitalWrite(N_PIN_IN1, LOW);
    digitalWrite(N_PIN_IN2, LOW);
    digitalWrite(N_PIN_IN3, LOW);
    digitalWrite(N_PIN_IN4, LOW);
}

void f_set_rpm(float rpm) {
    // n_us_step_delay = microseconds per half-step
    // one revolution = N_HALFSTEP_PER_REV half-steps
    // at X RPM: X revolutions per 60 seconds
    // steps per second = X * N_HALFSTEP_PER_REV / 60
    // delay per step = 60_000_000 / (X * N_HALFSTEP_PER_REV)
    if (rpm < 0.1) rpm = 0.1;
    n_us_step_delay = (unsigned long)(60000000.0 / (rpm * N_HALFSTEP_PER_REV));
}

void f_step(int n_count) {
    // positive = clockwise, negative = counter-clockwise
    int n_dir = (n_count > 0) ? 1 : -1;
    int n_abs = abs(n_count);
    for (int i = 0; i < n_abs; i++) {
        n_phase = (n_phase + n_dir + 8) % 8;
        f_set_phase(n_phase);
        delayMicroseconds(n_us_step_delay);
    }
    f_stepper_off();
}

int f_n_halfstep__from_deg(int n_deg) {
    return (int)((long)n_deg * N_HALFSTEP_PER_REV / 360);
}

WebSocketsClient o_ws;
WebServer o_http(80);
Preferences o_prefs;

bool b_running = false;
bool b_ws_connected = false;
unsigned long n_ms_start = 0;
unsigned long n_ms_duration = 0;

// ── NVS load/save ──

void f_load_config() {
    o_prefs.begin("teedunker", true); // read-only
    s_wifi_ssid       = o_prefs.getString("wifi_ssid", S_WIFI_SSID_DEFAULT);
    s_wifi_password   = o_prefs.getString("wifi_pass", S_WIFI_PASSWORD_DEFAULT);
    s_server_ip       = o_prefs.getString("srv_ip", S_SERVER_IP_DEFAULT);
    n_server_port     = o_prefs.getInt("srv_port", N_SERVER_PORT_DEFAULT);
    n_turn__loop      = o_prefs.getFloat("turn_loop", 0.5);
    n_turn__last      = o_prefs.getInt("turn_last", 2);
    n_min_duration    = o_prefs.getInt("min_dur", 4);
    n_rpm             = o_prefs.getFloat("rpm", 14);
    o_prefs.end();
    Serial.println("[nvs] config loaded");
}

void f_save_config() {
    o_prefs.begin("teedunker", false); // read-write
    o_prefs.putString("wifi_ssid", s_wifi_ssid);
    o_prefs.putString("wifi_pass", s_wifi_password);
    o_prefs.putString("srv_ip", s_server_ip);
    o_prefs.putInt("srv_port", n_server_port);
    o_prefs.putFloat("turn_loop", n_turn__loop);
    o_prefs.putInt("turn_last", n_turn__last);
    o_prefs.putInt("min_dur", n_min_duration);
    o_prefs.putFloat("rpm", n_rpm);
    o_prefs.end();
    Serial.println("[nvs] config saved");
}

// ── Helpers ──

void f_send_status() {
    if (!b_ws_connected) return;
    JsonDocument o_doc;
    o_doc["s_type"] = "esp32_status";
    o_doc["s_ip"] = WiFi.localIP().toString();
    o_doc["s_ssid"] = WiFi.SSID();
    o_doc["b_running"] = b_running;
    o_doc["n_ms_elapsed"] = b_running ? (millis() - n_ms_start) : 0;
    o_doc["n_turn__loop"] = n_turn__loop;
    o_doc["n_turn__last"] = n_turn__last;
    o_doc["n_min_duration"] = n_min_duration;
    o_doc["n_rpm"] = n_rpm;
    String s_json;
    serializeJson(o_doc, s_json);
    o_ws.sendTXT(s_json);
}

void f_run_procedure() {
    // one cycle: n_turn__loop revolutions forward, then n_turn__loop revolutions back
    f_set_rpm(n_rpm);
    int n_hs = (int)(n_turn__loop * N_HALFSTEP_PER_REV);
    Serial.println("[stepper] " + String(n_turn__loop, 1) + " turns forward @ " + String(n_rpm, 1) + " RPM");
    f_step(n_hs);
    Serial.println("[stepper] " + String(n_turn__loop, 1) + " turns backward");
    f_step(-n_hs);
}

void f_final_turn() {
    // end with n_turn__last revolutions forward (only after min duration reached)
    f_set_rpm(n_rpm);
    int n_hs = n_turn__last * N_HALFSTEP_PER_REV;
    Serial.println("[stepper] final " + String(n_turn__last) + " turns forward");
    f_step(n_hs);
}

// ── ESP32 config webpage ──

String f_s_html_page() {
    String s = "<!DOCTYPE html><html><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width,initial-scale=1'>";
    s += "<title>ESP32 Stepper Config</title>";
    s += "<style>";
    s += "body{font-family:system-ui,sans-serif;background:#1a1a2e;color:#e0e0e0;margin:0;padding:1rem;}";
    s += "h1{color:#8b74ea;font-size:1.3rem;}";
    s += ".section{background:rgba(255,255,255,0.05);border:1px solid rgba(255,255,255,0.1);border-radius:6px;padding:1rem;margin-bottom:0.75rem;}";
    s += "h2{font-size:0.85rem;color:#a0aec0;text-transform:uppercase;letter-spacing:0.05em;margin:0 0 0.5rem 0;}";
    s += "label{display:block;font-size:0.75rem;color:#718096;margin-top:0.4rem;}";
    s += "input,select{width:100%;padding:0.4rem;background:rgba(255,255,255,0.08);border:1px solid rgba(255,255,255,0.15);border-radius:4px;color:#e0e0e0;font:inherit;box-sizing:border-box;}";
    s += "input:focus,select:focus{border-color:#8b74ea;outline:none;}";
    s += "button{padding:0.6rem 1.5rem;background:rgba(139,116,234,0.2);color:#8b74ea;border:1px solid #8b74ea;border-radius:4px;cursor:pointer;font:inherit;font-weight:600;margin-top:0.75rem;}";
    s += "button:hover{opacity:0.8;}";
    s += ".status{font-size:0.85rem;color:#68d391;margin-top:0.5rem;}";
    s += ".row{display:flex;gap:0.5rem;} .row>div{flex:1;}";
    s += "</style></head><body>";
    s += "<h1>ESP32 Stepper Config</h1>";
    s += "<form method='POST' action='/save'>";

    // WiFi
    s += "<div class='section'><h2>WiFi</h2>";
    s += "<label>SSID</label><input name='wifi_ssid' value='" + s_wifi_ssid + "'>";
    s += "<label>Password</label><input name='wifi_pass' type='password' value='" + s_wifi_password + "'>";
    s += "</div>";

    // Server
    s += "<div class='section'><h2>Server WebSocket</h2>";
    s += "<div class='row'><div><label>IP</label><input name='srv_ip' value='" + s_server_ip + "'></div>";
    s += "<div><label>Port</label><input name='srv_port' type='number' value='" + String(n_server_port) + "'></div></div>";
    s += "</div>";

    // Stepper
    s += "<div class='section'><h2>Stepper Procedure</h2>";
    s += "<div class='row'><div><label>Turns per cycle (loop)</label><input name='turn_loop' type='number' step='0.1' min='0.1' value='" + String(n_turn__loop, 1) + "'></div>";
    s += "<div><label>Turns last (after min)</label><input name='turn_last' type='number' min='1' value='" + String(n_turn__last) + "'></div></div>";
    s += "<label>Duration (min)</label><input name='min_dur' type='number' value='" + String(n_min_duration) + "'>";
    s += "<label>Speed (RPM, 0.1 - 15.0)</label><input name='rpm' type='number' step='0.1' min='0.1' max='15.0' value='" + String(n_rpm, 1) + "'>";
    s += "</div>";

    // Status + control
    s += "<div class='section'><h2>Status & Control</h2>";
    s += "<div>IP: " + WiFi.localIP().toString() + "</div>";
    s += "<div>SSID: " + WiFi.SSID() + "</div>";
    s += "<div>Running: <strong>" + String(b_running ? "Yes" : "No") + "</strong></div>";
    if (b_running) {
        unsigned long n_ms_el = millis() - n_ms_start;
        unsigned long n_sec_remaining = (n_ms_duration > n_ms_el) ? (n_ms_duration - n_ms_el) / 1000 : 0;
        s += "<div>Remaining: " + String(n_sec_remaining) + "s</div>";
    }
    s += "</div>";

    s += "<button type='submit'>Save & Apply</button>";
    s += "</form>";

    // start/stop buttons (separate forms, not inside the config form)
    s += "<div class='section'><h2>Procedure</h2>";
    s += "<div class='row'>";
    s += "<div><form method='POST' action='/start'><button style='width:100%;background:rgba(104,211,145,0.2);color:#68d391;border-color:#68d391;'" + String(b_running ? " disabled" : "") + ">Start</button></form></div>";
    s += "<div><form method='POST' action='/stop'><button style='width:100%;background:rgba(252,129,129,0.2);color:#fc8181;border-color:#fc8181;'" + String(!b_running ? " disabled" : "") + ">Stop</button></form></div>";
    s += "</div></div>";

    s += "</body></html>";
    return s;
}

void f_handle_root() {
    o_http.send(200, "text/html", f_s_html_page());
}

void f_handle_save() {
    bool b_wifi_changed = false;
    bool b_ws_changed = false;

    if (o_http.hasArg("wifi_ssid")) {
        String s_new = o_http.arg("wifi_ssid");
        if (s_new != s_wifi_ssid) { s_wifi_ssid = s_new; b_wifi_changed = true; }
    }
    if (o_http.hasArg("wifi_pass")) {
        String s_new = o_http.arg("wifi_pass");
        if (s_new != s_wifi_password) { s_wifi_password = s_new; b_wifi_changed = true; }
    }
    if (o_http.hasArg("srv_ip")) {
        String s_new = o_http.arg("srv_ip");
        if (s_new != s_server_ip) { s_server_ip = s_new; b_ws_changed = true; }
    }
    if (o_http.hasArg("srv_port")) {
        int n_new = o_http.arg("srv_port").toInt();
        if (n_new != n_server_port) { n_server_port = n_new; b_ws_changed = true; }
    }
    if (o_http.hasArg("turn_loop"))  n_turn__loop   = max(0.1f, o_http.arg("turn_loop").toFloat());
    if (o_http.hasArg("turn_last"))  n_turn__last   = max(1, (int)o_http.arg("turn_last").toInt());
    if (o_http.hasArg("min_dur"))   n_min_duration = o_http.arg("min_dur").toInt();
    if (o_http.hasArg("rpm")) {
        n_rpm = constrain(o_http.arg("rpm").toFloat(), 0.1, 15.0);
        f_set_rpm(n_rpm);
    }

    f_save_config();

    if (b_running) {
        n_ms_duration = (unsigned long)n_min_duration * 60UL * 1000UL;
    }

    // redirect back to config page with saved confirmation
    String s_html = "<!DOCTYPE html><html><head><meta charset='UTF-8'><meta http-equiv='refresh' content='3;url=/'>";
    s_html += "<style>body{font-family:system-ui;background:#1a1a2e;color:#68d391;display:flex;align-items:center;justify-content:center;height:100vh;margin:0;}</style>";
    s_html += "</head><body><div><h2>Config saved!</h2><p>Redirecting...</p>";
    if (b_wifi_changed) s_html += "<p>WiFi changed — reconnecting...</p>";
    if (b_ws_changed) s_html += "<p>Server changed — reconnecting WebSocket...</p>";
    s_html += "</div></body></html>";
    o_http.send(200, "text/html", s_html);

    // apply WiFi change
    if (b_wifi_changed) {
        Serial.println("[config] WiFi changed, reconnecting...");
        WiFi.disconnect();
        delay(500);
        WiFi.begin(s_wifi_ssid.c_str(), s_wifi_password.c_str());
    }

    // apply WebSocket server change
    if (b_ws_changed) {
        Serial.println("[config] WebSocket server changed, reconnecting...");
        o_ws.disconnect();
        o_ws.begin(s_server_ip.c_str(), n_server_port, "/");
    }

    f_send_status();
}

void f_handle_start() {
    if (!b_running) {
        Serial.println("[http] start procedure");
        b_running = true;
        n_ms_start = millis();
        n_ms_duration = (unsigned long)n_min_duration * 60UL * 1000UL;
        f_send_status();
    }
    o_http.sendHeader("Location", "/");
    o_http.send(303);
}

void f_handle_stop() {
    if (b_running) {
        Serial.println("[http] stop procedure");
        b_running = false;
        f_send_status();
    }
    o_http.sendHeader("Location", "/");
    o_http.send(303);
}

// ── WebSocket event handler ──

void f_on_ws_event(WStype_t s_type, uint8_t* a_n_payload, size_t n_len) {
    switch (s_type) {
        case WStype_DISCONNECTED:
            Serial.println("[ws] disconnected");
            b_ws_connected = false;
            break;
        case WStype_CONNECTED:
            Serial.println("[ws] connected to server");
            b_ws_connected = true;
            {
                JsonDocument o_doc;
                o_doc["s_type"] = "esp32_hello";
                o_doc["s_ip"] = WiFi.localIP().toString();
                String s_json;
                serializeJson(o_doc, s_json);
                o_ws.sendTXT(s_json);
            }
            f_send_status();
            break;
        case WStype_TEXT: {
            String s_payload = String((char*)a_n_payload);
            JsonDocument o_doc;
            DeserializationError o_err = deserializeJson(o_doc, s_payload);
            if (o_err) {
                Serial.println("[ws] JSON parse error: " + String(o_err.c_str()));
                break;
            }
            String s_command = o_doc["s_command"] | "";

            if (s_command == "start") {
                Serial.println("[ws] command: start");
                b_running = true;
                n_ms_start = millis();
                n_ms_duration = (unsigned long)n_min_duration * 60UL * 1000UL;
                f_send_status();
            }
            else if (s_command == "stop") {
                Serial.println("[ws] command: stop");
                b_running = false;
                f_send_status();
            }
            else if (s_command == "reconfigure") {
                Serial.println("[ws] command: reconfigure");
                n_turn__loop = o_doc["n_turn__loop"] | n_turn__loop;
                n_turn__last = o_doc["n_turn__last"] | n_turn__last;
                n_min_duration = o_doc["n_min_duration"] | n_min_duration;
                if (o_doc.containsKey("n_rpm")) {
                    n_rpm = o_doc["n_rpm"];
                    f_set_rpm(n_rpm);
                }
                if (b_running) {
                    n_ms_duration = (unsigned long)n_min_duration * 60UL * 1000UL;
                }
                f_save_config();
                f_send_status();
            }
            else if (s_command == "status") {
                f_send_status();
            }
            break;
        }
        default:
            break;
    }
}

// ── Setup & Loop ──

void setup() {
    Serial.begin(115200);
    Serial.println();
    Serial.println("[setup] tee_dunker stepper control");

    // init stepper pins
    pinMode(N_PIN_IN1, OUTPUT);
    pinMode(N_PIN_IN2, OUTPUT);
    pinMode(N_PIN_IN3, OUTPUT);
    pinMode(N_PIN_IN4, OUTPUT);
    f_stepper_off();

    // load config from NVS (survives power cycles)
    f_load_config();
    f_set_rpm(n_rpm);

    // auto-start procedure immediately (WiFi is not required)
    Serial.println("[setup] auto-starting procedure");
    b_running = true;
    n_ms_start = millis();
    n_ms_duration = (unsigned long)n_min_duration * 60UL * 1000UL;

    // start WiFi in background (non-blocking)
    Serial.print("[wifi] connecting to ");
    Serial.println(s_wifi_ssid);
    WiFi.begin(s_wifi_ssid.c_str(), s_wifi_password.c_str());

    // start config web server on port 80
    o_http.on("/", f_handle_root);
    o_http.on("/save", HTTP_POST, f_handle_save);
    o_http.on("/start", HTTP_POST, f_handle_start);
    o_http.on("/stop", HTTP_POST, f_handle_stop);
    o_http.begin();
    Serial.println("[http] config server started on port 80");

    // connect WebSocket to desktop app server
    o_ws.begin(s_server_ip.c_str(), n_server_port, "/");
    o_ws.onEvent(f_on_ws_event);
    o_ws.setReconnectInterval(3000);

    Serial.println("[setup] ready");
}

void loop() {
    // handle WiFi/HTTP/WS only when connected (never blocks stepper)
    if (WiFi.status() == WL_CONNECTED) {
        o_ws.loop();
        o_http.handleClient();
    } else {
        // non-blocking reconnect attempt every 10 seconds
        static unsigned long n_ms_last_wifi_attempt = 0;
        if (millis() - n_ms_last_wifi_attempt > 10000) {
            n_ms_last_wifi_attempt = millis();
            Serial.println("[wifi] reconnecting...");
            WiFi.begin(s_wifi_ssid.c_str(), s_wifi_password.c_str());
        }
    }

    if (!b_running) {
        delay(10);
        return;
    }

    // check if duration elapsed
    unsigned long n_ms_elapsed = millis() - n_ms_start;
    if (n_ms_elapsed >= n_ms_duration) {
        Serial.println("[stepper] duration reached, performing final turn");
        f_final_turn();
        b_running = false;
        f_send_status();
        return;
    }

    f_run_procedure();

    // send periodic status (every 5 seconds)
    static unsigned long n_ms_last_status = 0;
    if (millis() - n_ms_last_status > 5000) {
        n_ms_last_status = millis();
        f_send_status();
    }
}
